// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjpuafljpygjfcusttds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcHVhZmxqcHlnamZjdXN0dGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTYzNTIsImV4cCI6MjA2MzA5MjM1Mn0.NDKH3B1wUgAfT3ryz6vOBewerzrHhjQJMYP3vRlgJDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);